services:
  - type: web
    name: puihaha-electric
    runtime: docker
    plan: free
    region: singapore
    healthCheckPath: /
    envVars:
      - key: CI_ENVIRONMENT
        value: production

      - key: database.default.hostname
        sync: false

      - key: database.default.database
        sync: false

      - key: database.default.username
        sync: false

      - key: database.default.password
        sync: false

      - key: database.default.DBDriver
        value: MySQLi

      - key: database.default.port
        value: "10816"

      - key: database.default.encrypt
        value: "true"