services:
  - type: web
    name: puihaha-electric
    runtime: docker
    plan: free
    region: singapore
    healthCheckPath: /
    envVars:
      - key: CI_ENVIRONMENT
        value: production

      - key: database_default_hostname
        sync: false

      - key: database_default_database
        sync: false

      - key: database_default_username
        sync: false

      - key: database_default_password
        sync: false

      - key: database_default_DBDriver
        value: MySQLi

      - key: database_default_port
        value: "10816"

      - key: database_default_encrypt
        value: "true"
